import { io } from "@iron/standard";

// Integers
let a: Integer = 1;     // Inferred precision.
let b: Integer(32) = 2; // Explicit precision. (16, 32, 64, 128, 256)

try {
  let c: UnsignedInt = -3;
} catch (error) {
  io.print_line("Unsigned integers cannot be negative.");
};

// Floats
let d = 123.456;                 // Types can also be inferred.
let e = 789.1011121314151617182; // Precision can be inferred as well.

// Strings
let do: String = "A (female) deer.";
let re = "A drop of golden sun.";
let mi = "A name I call myself";

// Characters
let a: Char = 'a';
let b = 'b';

try {
  let c: Char = "c";
} catch (error) {
  io.print_line("Characters must use single-quotes.");
};

// Booleans
let earth_is_flat: Boolean = true;
let sky_is_blue = false;

if earth_is_flat {
  io.print_line("Don't fall off!");
} else if sky_is_blue {
  io.print_line("Pretty!");
} else {
  io.print_line("What are facts anyway?");
}
